---
title: "Phenotype Analysis"
author: "David LeBauer, Craig Willis"
date: "`r Sys.Date()`"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
library(jsonlite)
library(dplyr)
library(ggplot2)
theme_set(theme_bw())
library(traits)
```


## BETYdb

BETYdb stores trait data and agronomic metadata. An introduction to the API is in ../betydb.md

Also see the full documentation for accessing data from BETYdb. 


```{r traits}
terraref_betyurl <- "https://terraref.ncsa.illinois.edu/bety/"
mykey = readLines(con = file('~/.betykey'))
site <- betydb_site(id = 6000000866, betyurl = terraref_betyurl, key = mykey)

sorghum_all <- betydb_search(query = 'Sorghum', 
                         betyurl = terraref_betyurl, 
                         key = mykey) 
#save(sorghum_all, file = '~/terraref/documentation/tutorials/data/sorghum_all.RData')
#load('~/terraref/documentation/tutorials/data/sorghum_all.RData')

sorghum <- sorghum_all %>% 
  select(author, date, scientificname, cultivar, entity, trait, mean, units, city, sitename)

head(sorghum)

```

### Summary of Available Data

```{r phenotype_counts, fig.width=8, fig.height=4}

ggplot(data = sorghum) + 
  geom_histogram(aes(x = mean), bins = 100) + 
  facet_wrap(~trait, scales = 'free')


```


### Danfoth Phenotyping Facility 
```{r danforth-phenotypes, fig.width=8, fig.height=4}
danforth <- sorghum %>% 
  filter(author == 'Fahlgren, Noah') %>% 
  mutate(date = lubridate::ymd(date))
  

ggplot(data = danforth, aes(x = date, y = mean, color = cultivar)) +
  #geom_line(aes(y = mean, group = entity), alpha = 0.1) +
  geom_smooth() +
  geom_point(alpha = 0.1, size = 0.5) +
  facet_wrap(~trait, scales = 'free')
```
